language: c
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - cmake .
  - cmake --build . -- VERBOSE=1
  - valgrind --leak-check=yes --error-exitcode=1 ./gmsd_tests